# parserOptions:
#   ecmaVersion: 2018
#   sourceType: 'module'

# env:
#   es2017: true
#   browser: true

# extends: 'htmlacademy/vanilla'

parserOptions:
  sourceType: 'module'
  ecmaVersion: 2015
  
env:
  es6: true
  browser: true

extends: 'htmlacademy/es6'
